// js/ratings.js
function generateStars(rating) {
    if (rating == null) return '';
    const fullStars = Math.floor(rating);
    const hasHalf = rating % 1 !== 0;
    let html = '';
    for (let i = 0; i < fullStars; i++) html += '<i class="fas fa-star" style="color: #FFC107;"></i>';
    if (hasHalf) html += '<i class="fas fa-star-half-alt" style="color: #FFC107;"></i>';
    for (let i = fullStars + (hasHalf ? 1 : 0); i < 5; i++) html += '<i class="far fa-star" style="color: #E0E0E0;"></i>';
    return html;
}

function ratingFromViews(views) {
    const count = Math.max(0, parseInt(views, 10) || 0);
    if (count === 0) return null;

    let rating;
    if (count <= 50) {
        rating = 3.8 + (count / 50) * 0.7;
    } else if (count <= 500) {
        rating = 4.5 + ((count - 50) / 450) * 0.3;
    } else {
        rating = 4.8 + Math.min(0.2, Math.log10(count / 500) * 0.05);
    }

    return Math.min(5, Math.round(rating * 10) / 10);
}

function getProductRating(product) {
    if (product.rating != null) return parseFloat(product.rating);
    const views = parseInt(product.views, 10);
    if (!Number.isNaN(views) && views > 0) return ratingFromViews(views);
    return null;
}

function mergeRatingsData(products, ratingsMap) {
    /* ── IMPORTANT: always lowercase product IDs before map lookup ───────────────
       ratingsMap keys are generated by normalizeSheetId() → lowercase.
       Google Sheets IDs may arrive in uppercase (abc001 ← ABC001).
       Using .toLowerCase() here prevents mismatches between product IDs and
       their ratings/views data. */
    if (!ratingsMap || typeof ratingsMap !== 'object') return;
    products.forEach(product => {
        const productId = String(product.id).toLowerCase();
        const data = ratingsMap[productId];
        console.log('mergeRatingsData | Product ID:', product.id, '| Lowercase Key:', productId, '| Data Found:', !!data, data);

        if (data) {
            const views = typeof data === 'object' ? parseInt(data.views, 10) : parseInt(data, 10);
            const ratingFromData = (typeof data === 'object' && data.rating != null) ? parseFloat(data.rating) : null;
            const ratingCountFromData = (typeof data === 'object' && data.ratingCount != null) ? parseInt(data.ratingCount, 10) : null;

            if (!Number.isNaN(views)) {
                product.views = views;
                product.rating = (ratingFromData !== null) ? ratingFromData : (product.rating != null ? parseFloat(product.rating) : ratingFromViews(views));
                product.ratingCount = (ratingCountFromData !== null) ? ratingCountFromData : (product.ratingCount || 0);
            } else {
                product.views = product.views || 0;
                product.rating = (ratingFromData !== null) ? ratingFromData : (product.rating != null ? parseFloat(product.rating) : null);
                product.ratingCount = (ratingCountFromData !== null) ? ratingCountFromData : 0;
            }
        }
    });
    markMostViewedProducts();
}

function updateModalRating(product) {
    const ratingEl = document.getElementById('mRating');
    if (!ratingEl || !product) return;

    const rating = getProductRating(product);
    const stars = rating != null ? generateStars(rating) : '';
    const ratingCount = product.ratingCount || 0;
    const displayRating = rating != null ? rating.toFixed(1) : '—';
    ratingEl.innerHTML = `${stars}<span>(${displayRating} من 5)${ratingCount > 0 ? '<br><span style="font-size:12px;color:var(--text-muted)">' + ratingCount + ' تقييم</span>' : ''}</span>`;
}
